[package]
authors = ["Neil Ashford <ashfordneil0@gmail.com>"]
name = "engine"
version = "0.1.0"

[dependencies]
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"
toml = "0.4.5"

[dependencies.common]
path = "../common"
