[package]
name = "backend"
version = "0.1.0"
authors = ["Neil Ashford <ashfordneil0@gmail.com>"]

[dependencies]
common = { path = "common" }
funnel = { path = "funnel" }
engine = { path = "engine" }

[workspace]
